from __future__ import annotations

import os
from typing import Any, Dict, List, Tuple

from .parser import parse_metadata


_EDM_TO_PY: Dict[str, str] = {
    "Edm.String": "str",
    "Edm.Int16": "int",
    "Edm.Int32": "int",
    "Edm.Int64": "int",
    "Edm.SByte": "int",
    "Edm.Byte": "int",
    "Edm.Decimal": "float",
    "Edm.Double": "float",
    "Edm.Single": "float",
    "Edm.Boolean": "bool",
    "Edm.Guid": "str",
    "Edm.DateTimeOffset": "str",
    "Edm.Date": "str",
    "Edm.TimeOfDay": "str",
    "Edm.Duration": "str",
    "Edm.Binary": "bytes",
    "Edm.Stream": "bytes",
    "Edm.Untyped": "Any",
    "Edm.Geometry": "Any",
    "Edm.Geography": "Any",
    "Edm.GeographyPoint": "Any",
    "Edm.GeometryPoint": "Any",
}


def _last_segment(fqn: str) -> str:
    return fqn.split(".")[-1]


def _split_collection(type_str: str) -> Tuple[bool, str]:


def _resolve_underlying(type_str: str, model: Dict[str, Any]) -> str:
    # If this is a TypeDefinition, resolve to its underlying EDM type; otherwise return as-is
    if type_str in model.get("type_defs", {}):
        return model["type_defs"][type_str].get("underlying", type_str)
    return type_str


def _to_py_hint(prop_name: str, type_str: str, model: Dict[str, Any]) -> Tuple[str, str, bool]:
    """Return (annotation, base_for_check, is_collection).

    - annotation: string used in function signature, e.g. Optional[str] or Optional[List[int]]
    - base_for_check: runtime isinstance check target (e.g. str, int, ClassName) or 'Any' to skip
    - is_collection: whether the type is a collection
    """
    is_coll, inner = _split_collection(type_str)
    # Time-like fields accept multiple representations; keep them flexible as Any
    if prop_name in {"phenomenonTime", "resultTime", "validTime", "time", "creationTime"}:
        base_py = "Any"
    else:
        underlying = _resolve_underlying(inner, model)
        if underlying.startswith("Edm."):
            base_py = _EDM_TO_PY.get(underlying, "Any")
        else:
            last = _last_segment(underlying)
            # Open types or unknown complex types should remain flexible
            if last in {"Object", "ANY"}:
                base_py = "Any"
            else:
                base_py = last
    ann = f"Optional[List[{base_py}]]" if is_coll else f"Optional[{base_py}]"
    return ann, base_py, is_coll


def generate_from_metadata(xml_text: str, out_dir: str, module_name: str = "datamodel", source_url: str = "", odata_version: str = "") -> str:
    """Generate Python source for the OData model; classes align with frost_sta_client.model patterns.

    - Entities inherit from frost_sta_client.model.entity.Entity
    - Navigation collections use frost_sta_client.model.ext.entity_list.EntityList
    - __getstate__/__setstate__ follow SensorThings/OData JSON field names
    - Equality mirrors base behaviour plus scalar/complex property checks
    - Service propagation to child objects/lists is provided

    Returns: absolute path of the generated module file.
    """
    model = parse_metadata(xml_text)


    def snake(name: str) -> str:
        # Convert PascalCase/camelCase to snake_case for attribute names
        out: List[str] = []
        prev_is_lower = False
        for ch in name:
            if ch.isupper():
                if prev_is_lower:
                    out.append('_')
                out.append(ch.lower())
                prev_is_lower = False
            else:
                out.append(ch)
                prev_is_lower = ch.isalpha()
        return ''.join(out)


    def is_time_like(odata_name: str) -> bool:
        # Common SensorThings time fields
        return odata_name in {"phenomenonTime", "resultTime", "validTime", "time", "creationTime"}

    lines: List[str] = []
    lines.append("from __future__ import annotations")
    lines.append("# Auto-generated by FROST-STA OData codegen. Do not edit manually.")
    if source_url:
        lines.append(f"# Source: {source_url}")
    if odata_version:
        lines.append(f"# OData Version: {odata_version}")
    lines.append("from typing import Any, List, Optional")
    lines.append("from frost_sta_client import utils")
    lines.append("from frost_sta_client.model.entity import Entity")
    lines.append("from frost_sta_client.model.ext.entity_list import EntityList")
    lines.append("")

    exported: List[str] = []

    # Complex Types: Simple containers with (de)serialization and equality
    for fqn, cplx in model.get("complex_types", {}).items():
        c_name = cplx["name"]
        exported.append(c_name)
        props = cplx.get("properties", [])
        # Build typed __init__ signature for complex types (EDM primitives get concrete types)
        arg_parts = []
        for p in props:
            ann, _base_check, _is_coll = _to_py_hint(p['name'], p['type'], model)
            arg_parts.append(f"{snake(p['name'])}: {ann} = None")
        args = ", ".join(arg_parts)
        lines.append(f"class {c_name}:")
        lines.append(f"    def __init__(self, {args}):" if args else "    def __init__(self):")
        if not props:
            lines.append("        pass")
        else:
            # Runtime type checks for complex type properties
            for p in props:
                on = p['name']
                sn = snake(on)
                _ann, base_check, is_coll = _to_py_hint(on, p['type'], model)
                if base_check != "Any":
                    if is_coll:
                        lines.append(f"        if {sn} is not None:")
                        lines.append(f"            if not isinstance({sn}, list) or not all(isinstance(x, {base_check}) for x in {sn}):")
                        lines.append(f"                raise ValueError('{sn} should be a list of {base_check}')")
                    else:
                        lines.append(f"        if {sn} is not None and not isinstance({sn}, {base_check}):")
                        lines.append(f"            raise ValueError('{sn} should be of type {base_check}!')")
                lines.append(f"        self.{sn} = {sn}")
        lines.append("")
        lines.append("    def __getstate__(self):")
        lines.append("        d = {}")
        for p in props:
            on = p['name']
            sn = snake(on)
            lines.append(f"        if self.{sn} is not None:")
            lines.append(f"            d['{on}'] = self.{sn}")
        lines.append("        return d")
        lines.append("")
        lines.append("    def __setstate__(self, state):")
        for p in props:
            on = p['name']
            sn = snake(on)
            lines.append(f"        self.{sn} = state.get('{on}', None)")
        lines.append("")
        lines.append("    def __eq__(self, other):")
        lines.append("        if other is None or not isinstance(other, type(self)):")
        lines.append("            return False")
        if props:
            cmp_expr = " and ".join([f"self.{snake(p['name'])} == other.{snake(p['name'])}" for p in props])
            lines.append(f"        return {cmp_expr}")
        else:
            lines.append("        return True")
        lines.append("")

    # Entity Types: Entity-compatible classes
    for fqn, et in model.get("entity_types", {}).items():
        e_name = et["name"]
        exported.append(e_name)
        props = et.get("properties", [])
        navs = et.get("navigation_properties", [])

        arg_parts: List[str] = []
        # Build typed __init__ signature for entity types (EDM primitives get concrete types)
        arg_parts: List[str] = []
        for p in props:
            ann, _base_check, _is_coll = _to_py_hint(p['name'], p['type'], model)
            arg_parts.append(f"{snake(p['name'])}: {ann} = None")
        arg_sig = ", ".join(arg_parts)

        lines.append(f"class {e_name}(Entity):")
        lines.append(f"    def __init__(self, {arg_sig}, **kwargs):" if arg_sig else "    def __init__(self, **kwargs):")
        lines.append("        super().__init__(**kwargs)")
        # Runtime type checks for entity properties
        for p in props:
            on = p['name']
            sn = snake(on)
            _ann, base_check, is_coll = _to_py_hint(on, p['type'], model)
            if base_check != "Any":
                if is_coll:
                    lines.append(f"        if {sn} is not None:")
                    lines.append(f"            if not isinstance({sn}, list) or not all(isinstance(x, {base_check}) for x in {sn}):")
                    lines.append(f"                raise ValueError('{sn} should be a list of {base_check}')")
                else:
                    lines.append(f"        if {sn} is not None and not isinstance({sn}, {base_check}):")
                    lines.append(f"            raise ValueError('{sn} should be of type {base_check}!')")
        for p in props:
            sn = snake(p['name'])
            lines.append(f"        self.{sn} = {sn}")
        for np in navs:
            sn = snake(np['name'])
            lines.append(f"        self.{sn} = None")
        lines.append("")

        # Service propagation
        lines.append("    def ensure_service_on_children(self, service):")
        if not navs:
            lines.append("        pass")
        else:
            for np in navs:
                sn = snake(np['name'])
                lines.append(f"        if self.{sn} is not None:")
                lines.append(f"            self.{sn}.set_service(service)")
        lines.append("")

        # Equality
        lines.append("    def __eq__(self, other):")
        lines.append("        if not super().__eq__(other):")
        lines.append("            return False")
        if props:
            for p in props:
                sn = snake(p['name'])
                lines.append(f"        if self.{sn} != other.{sn}:")
                lines.append("            return False")
            lines.append("        return True")
        else:
            lines.append("        return True")
        lines.append("")

        # __getstate__
        lines.append("    def __getstate__(self):")
        lines.append("        data = super().__getstate__()")
        for p in props:
            on = p['name']
            sn = snake(on)
            lines.append(f"        if self.{sn} is not None:")
            if is_time_like(on):
                lines.append(f"            data['{on}'] = utils.parse_datetime(self.{sn})")
            else:
                lines.append(f"            data['{on}'] = self.{sn}")
        for np in navs:
            on = np['name']
            sn = snake(on)
            if np.get("collection", False):
                lines.append(f"        if self.{sn} is not None and len(self.{sn}.entities) > 0:")
                lines.append(f"            data['{on}'] = self.{sn}.__getstate__()")
            else:
                lines.append(f"        if self.{sn} is not None:")
                lines.append(f"            data['{on}'] = self.{sn}.__getstate__()")
        lines.append("        return data")
        lines.append("")

        # __setstate__
        lines.append("    def __setstate__(self, state):")
        lines.append("        super().__setstate__(state)")
        for p in props:
            on = p['name']
            sn = snake(on)
            lines.append(f"        self.{sn} = state.get('{on}', None)")
        for np in navs:
            on = np['name']
            sn = snake(on)
            related = _last_segment(np['type'])
            if np.get("collection", False):
                lines.append(f"        if state.get('{on}', None) is not None and isinstance(state['{on}'], list):")
                lines.append(f"            self.{sn} = utils.transform_json_to_entity_list(state['{on}'], __name__ + '.{related}')")
                lines.append(f"            self.{sn}.next_link = state.get('{on}@iot.nextLink', None)")
                lines.append(f"            self.{sn}.count = state.get('{on}@iot.count', None)")
            else:
                lines.append(f"        if state.get('{on}', None) is not None:")
                lines.append(f"            self.{sn} = {related}()")
                lines.append(f"            self.{sn}.__setstate__(state['{on}'])")
        lines.append("")

    # EntitySets mapping
    lines.append("# Map EntitySet name -> class")
    lines.append("ENTITY_SETS = {")
    for es, fqn in model.get("entity_sets", {}).items():
        lines.append(f"    '{es}': {_last_segment(fqn)},")
    lines.append("}")
    lines.append("")

    # __all__
    exported.extend(list(model.get("entity_sets", {}).keys()))
    lines.append("__all__ = [")
    for name in sorted(set(exported)):
        lines.append(f"    '{name}',")
    lines.append("]")
    lines.append("")

    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, f"{module_name}.py")
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    return out_path


def generate_from_url(base_url: str, out_dir: str, module_name: str = "datamodel", auth: Any = None) -> str:
    """Detect an OData endpoint and generate models accordingly.

    Fallback: If no OData endpoint is available, use project's metadata.xml.
    """
    from .runtime import find_odata_endpoint, fetch_metadata
    info = find_odata_endpoint(base_url, auth=auth)
    if info is None:
        meta_path_candidates = [
            os.path.join(os.getcwd(), "metadata.xml"),
            os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "metadata.xml"),
        ]
        xml_text = None
        source = None
        for p in meta_path_candidates:
            try:
                if os.path.exists(p):
                    with open(p, "r", encoding="utf-8") as fh:
                        xml_text = fh.read()
                        source = p
                        break
            except Exception:
                pass
        if not xml_text:
            raise RuntimeError("No OData endpoint detected and metadata.xml not found. No code generated.")
        return generate_from_metadata(xml_text, out_dir, module_name, source_url=source or "", odata_version="4.01")
    xml = fetch_metadata(info["metadata_url"], auth=auth)
    return generate_from_metadata(xml, out_dir, module_name, source_url=info["metadata_url"], odata_version=info["version"])
