from __future__ import annotations

import os
from typing import Any, Dict, List, Tuple

from .parser import parse_metadata

_EDM_TO_PY: Dict[str, str] = {
    "Edm.String": "str",
    "Edm.Int16": "int",
    "Edm.Int32": "int",
    "Edm.Int64": "int",
    "Edm.SByte": "int",
    "Edm.Byte": "int",
    "Edm.Decimal": "float",
    "Edm.Double": "float",
    "Edm.Single": "float",
    "Edm.Boolean": "bool",
    "Edm.Guid": "str",
    "Edm.DateTimeOffset": "str",
    "Edm.Date": "str",
    "Edm.TimeOfDay": "str",
    "Edm.Duration": "str",
    "Edm.Binary": "bytes",
    "Edm.Stream": "bytes",
    # OData/Geo/Open Types -> Any
    "Edm.Untyped": "Any",
    "Edm.Geometry": "Any",
    "Edm.Geography": "Any",
    "Edm.GeographyPoint": "Any",
    "Edm.GeometryPoint": "Any",
}

def _last_segment(fqn: str) -> str:
    return fqn.split(".")[-1]

def _py_type_for_type_ref(type_ref: str) -> str:
    # For FQN types, return class name
    if type_ref in _EDM_TO_PY:
        return _EDM_TO_PY[type_ref]
    # Assume FQN or already simple name -> return last segment
    return _last_segment(type_ref)

def _opt(type_str: str, nullable: bool) -> str:
    if nullable:
        return f"Optional[{type_str}]"
    return type_str

def _collection(type_str: str) -> str:
    return f"List[{type_str}]"

def _split_collection(type_str: str) -> Tuple[bool, str]:
    if type_str.startswith("Collection(") and type_str.endswith(")"):
        return True, type_str[len("Collection("):-1]
    return False, type_str

def generate_from_metadata(xml_text: str, out_dir: str, module_name: str = "datamodel", source_url: str = "", odata_version: str = "") -> str:
    """Generate Python code from OData metadata XML.

    Returns the path to the created module file.
    """
    model = parse_metadata(xml_text)

    lines: List[str] = []
    lines.append("from __future__ import annotations")
    lines.append("# Auto-generated by FROST-STA OData codegen. Do not edit manually.")
    if source_url:
        lines.append(f"# Source: {source_url}")
    if odata_version:
        lines.append(f"# OData Version: {odata_version}")
    lines.append("from dataclasses import dataclass, field")
    lines.append("from typing import Optional, List, Any")
    lines.append("from enum import Enum")
    lines.append("")

    exported: List[str] = []

    # Type definitions as simple alias assignments
    for fqn, td in model.get("type_defs", {}).items():
        alias = td["name"]
        underlying = _py_type_for_type_ref(td.get("underlying", "Edm.String"))
        lines.append(f"{alias} = {underlying}")
        exported.append(alias)
    if model.get("type_defs"):
        lines.append("")

    # Enums
    for fqn, enum in model.get("enum_types", {}).items():
        en_name = enum["name"]
        exported.append(en_name)
        lines.append(f"class {en_name}(Enum):")
        members = enum.get("members", [])
        if not members:
            lines.append("    pass")
        else:
            for mname, mval in members:
                if mname is None:
                    continue
                if mval is None:
                    lines.append(f"    {mname} = '{mname}'")
                else:
                    lines.append(f"    {mname} = {mval}")
        lines.append("")

    # Complex types
    for fqn, cplx in model.get("complex_types", {}).items():
        c_name = cplx["name"]
        exported.append(c_name)
        lines.append(f"@dataclass")
        lines.append(f"class {c_name}:")
        props = cplx.get("properties", [])
        if not props:
            lines.append("    pass")
        else:
            for p in props:
                raw_type = p.get("type", "Edm.String")
                is_coll, inner = _split_collection(raw_type)
                if is_coll:
                    inner_py = _py_type_for_type_ref(inner)
                    ptype = _collection(inner_py)
                    lines.append(f"    {p['name']}: {ptype} = field(default_factory=list)")
                else:
                    ptype = _py_type_for_type_ref(raw_type)
                    ptype = _opt(ptype, p.get("nullable", True))
                    lines.append(f"    {p['name']}: {ptype} = None")
        lines.append("")

    # EntityTypes
    for fqn, et in model.get("entity_types", {}).items():
        e_name = et["name"]
        exported.append(e_name)
        lines.append(f"@dataclass")
        lines.append(f"class {e_name}:")
        props = et.get("properties", [])
        keys = set(et.get("keys", []))
        has_any = False
        # normal properties
        for p in props:
            raw_type = p.get("type", "Edm.String")
            is_coll, inner = _split_collection(raw_type)
            if is_coll:
                inner_py = _py_type_for_type_ref(inner)
                nptype = _collection(inner_py)
                lines.append(f"    {p['name']}: {nptype} = field(default_factory=list)")
            else:
                ptype = _py_type_for_type_ref(raw_type)
                # Keys sind i.d.R. nicht nullable
                nullable = p.get("nullable", True) and (p.get("name") not in keys)
                ptype = _opt(ptype, nullable)
                lines.append(f"    {p['name']}: {ptype} = None")
            has_any = True
        # navigation properties
        for np in et.get("navigation_properties", []):
            nptype = _py_type_for_type_ref(np.get("type", "Edm.EntityType"))
            if np.get("collection", False):
                nptype = _collection(nptype)
                lines.append(f"    {np['name']}: {nptype} = field(default_factory=list)")
            else:
                nptype = _opt(nptype, True)
                lines.append(f"    {np['name']}: {nptype} = None")
            has_any = True
        if not has_any:
            lines.append("    pass")
        lines.append("")

    # EntitySets mapping
    lines.append("# Map EntitySet name -> class")
    lines.append("ENTITY_SETS = {")
    for es, fqn in model.get("entity_sets", {}).items():
        lines.append(f"    '{es}': {_last_segment(fqn)},")
    lines.append("}")
    lines.append("")

    exported.extend(list(model.get("entity_sets", {}).keys()))
    # __all__
    lines.append("__all__ = [")
    for name in sorted(set(exported)):
        lines.append(f"    '{name}',")
    lines.append("]")
    lines.append("")

    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, f"{module_name}.py")
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    return out_path

def generate_from_url(base_url: str, out_dir: str, module_name: str = "datamodel", auth: Any = None) -> str:
    """Detect OData endpoint from base_url and generate models to out_dir/module_name.py.

    Fallback: if no OData endpoint exists, use metadata.xml from the project directory.
    """
    from .runtime import find_odata_endpoint, fetch_metadata
    info = find_odata_endpoint(base_url, auth=auth)
    if info is None:
        # Fallback: local metadata.xml as default
        meta_path_candidates = [
            os.path.join(os.getcwd(), "metadata.xml"),
            os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "metadata.xml"),
        ]
        xml_text = None
        for p in meta_path_candidates:
            try:
                if os.path.exists(p):
                    with open(p, "r", encoding="utf-8") as fh:
                        xml_text = fh.read()
                        source = p
                        break
            except Exception:
                pass
        if not xml_text:
            raise RuntimeError("No OData endpoint detected and metadata.xml not found. No code generated.")
        return generate_from_metadata(xml_text, out_dir, module_name, source_url=source, odata_version="4.01")
    xml = fetch_metadata(info["metadata_url"], auth=auth)
    return generate_from_metadata(xml, out_dir, module_name, source_url=info["metadata_url"], odata_version=info["version"])
