from __future__ import annotations

import os
from typing import Any, Dict, List, Tuple

from .parser import parse_metadata

_EDM_TO_PY: Dict[str, str] = {
    "Edm.String": "str",
    "Edm.Int16": "int",
    "Edm.Int32": "int",
    "Edm.Int64": "int",
    "Edm.SByte": "int",
    "Edm.Byte": "int",
    "Edm.Decimal": "float",
    "Edm.Double": "float",
    "Edm.Single": "float",
    "Edm.Boolean": "bool",
    "Edm.Guid": "str",
    "Edm.DateTimeOffset": "str",
    "Edm.Date": "str",
    "Edm.TimeOfDay": "str",
    "Edm.Duration": "str",
    "Edm.Binary": "bytes",
    "Edm.Stream": "bytes",
    # Geo types and unknowns default to Any
}

def _last_segment(fqn: str) -> str:
    return fqn.split(".")[-1]

def _py_type_for_type_ref(type_ref: str) -> str:
    # For FQN types, return class name
    if type_ref in _EDM_TO_PY:
        return _EDM_TO_PY[type_ref]
    # Assume FQN or already simple name -> return last segment
    return _last_segment(type_ref)

def _opt(type_str: str, nullable: bool) -> str:
    if nullable:
        return f"Optional[{type_str}]"
    return type_str

def _collection(type_str: str) -> str:
    return f"List[{type_str}]"

def generate_from_metadata(xml_text: str, out_dir: str, module_name: str = "datamodel", source_url: str = "", odata_version: str = "") -> str:
    """Generate Python code from OData metadata XML.

    Returns the path to the created module file.
    """
    model = parse_metadata(xml_text)

    lines: List[str] = []
    lines.append("from __future__ import annotations")
    lines.append("# Auto-generated by FROST-STA OData codegen. Do not edit manually.")
    if source_url:
        lines.append(f"# Source: {source_url}")
    if odata_version:
        lines.append(f"# OData Version: {odata_version}")
    lines.append("from dataclasses import dataclass, field")
    lines.append("from typing import Optional, List, Any")
    lines.append("from enum import Enum")
    lines.append("")

    exported: List[str] = []

    # Enums
    for fqn, enum in model.get("enum_types", {}).items():
        en_name = enum["name"]
        exported.append(en_name)
        lines.append(f"class {en_name}(Enum):")
        members = enum.get("members", [])
        if not members:
            lines.append("    pass")
        else:
            for mname, mval in members:
                if mname is None:
                    continue
                if mval is None:
                    lines.append(f"    {mname} = '{mname}'")
                else:
                    lines.append(f"    {mname} = {mval}")
        lines.append("")

    # Complex types
    for fqn, cplx in model.get("complex_types", {}).items():
        c_name = cplx["name"]
        exported.append(c_name)
        lines.append(f"@dataclass")
        lines.append(f"class {c_name}:")
        props = cplx.get("properties", [])
        if not props:
            lines.append("    pass")
        else:
            for p in props:
                ptype = _py_type_for_type_ref(p.get("type", "Edm.String"))
                ptype = _opt(ptype, p.get("nullable", True))
                lines.append(f"    {p['name']}: {ptype} = None")
        lines.append("")

    # Entity types
    for fqn, et in model.get("entity_types", {}).items():
        e_name = et["name"]
        exported.append(e_name)
        lines.append(f"@dataclass")
        lines.append(f"class {e_name}:")
        props = et.get("properties", [])
        keys = set(et.get("keys", []))
        has_any = False
        for p in props:
            ptype = _py_type_for_type_ref(p.get("type", "Edm.String"))
            # Keys are typically non-nullable
            nullable = p.get("nullable", True) and (p.get("name") not in keys)
            ptype = _opt(ptype, nullable)
            lines.append(f"    {p['name']}: {ptype} = None")
            has_any = True
        for np in et.get("navigation_properties", []):
            nptype = _py_type_for_type_ref(np.get("type", "Edm.EntityType"))
            if np.get("collection", False):
                nptype = _collection(nptype)
                lines.append(f"    {np['name']}: {nptype} = field(default_factory=list)")
            else:
                nptype = _opt(nptype, True)
                lines.append(f"    {np['name']}: {nptype} = None")
            has_any = True
        if not has_any:
            lines.append("    pass")
        lines.append("")

    # EntitySets mapping
    lines.append("# Map EntitySet name -> class")
    lines.append("ENTITY_SETS = {")
    for es, fqn in model.get("entity_sets", {}).items():
        lines.append(f"    '{es}': {_last_segment(fqn)},")
    lines.append("}")
    lines.append("")

    exported.extend(list(model.get("entity_sets", {}).keys()))
    # __all__
    lines.append("__all__ = [")
    for name in sorted(set(exported)):
        lines.append(f"    '{name}',")
    lines.append("]")
    lines.append("")

    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, f"{module_name}.py")
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    return out_path

def generate_from_url(base_url: str, out_dir: str, module_name: str = "datamodel", auth: Any = None) -> str:
    """Detect OData endpoint from base_url and generate models to out_dir/module_name.py.

    Returns the path to the created module file. Raises RuntimeError if no OData endpoint is found.
    """
    from .runtime import find_odata_endpoint, fetch_metadata
    info = find_odata_endpoint(base_url, auth=auth)
    if info is None:
        raise RuntimeError("No OData endpoint detected. Falling back to SensorThings model (no code generated).")
    xml = fetch_metadata(info["metadata_url"], auth=auth)
    return generate_from_metadata(xml, out_dir, module_name, source_url=info["metadata_url"], odata_version=info["version"])
